// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.21.12
// source: proto/analytics.proto

package ingestionv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TargetType int32

const (
	TargetType_UFO            TargetType = 0
	TargetType_CRUISE_MISSILE TargetType = 1
	TargetType_DRONE          TargetType = 2
	TargetType_HELICOPTER     TargetType = 3
	TargetType_FIGHTER_JET    TargetType = 4
	TargetType_UAV            TargetType = 5
	TargetType_AIRPLANE       TargetType = 6
)

// Enum value maps for TargetType.
var (
	TargetType_name = map[int32]string{
		0: "UFO",
		1: "CRUISE_MISSILE",
		2: "DRONE",
		3: "HELICOPTER",
		4: "FIGHTER_JET",
		5: "UAV",
		6: "AIRPLANE",
	}
	TargetType_value = map[string]int32{
		"UFO":            0,
		"CRUISE_MISSILE": 1,
		"DRONE":          2,
		"HELICOPTER":     3,
		"FIGHTER_JET":    4,
		"UAV":            5,
		"AIRPLANE":       6,
	}
)

func (x TargetType) Enum() *TargetType {
	p := new(TargetType)
	*p = x
	return p
}

func (x TargetType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TargetType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_analytics_proto_enumTypes[0].Descriptor()
}

func (TargetType) Type() protoreflect.EnumType {
	return &file_proto_analytics_proto_enumTypes[0]
}

func (x TargetType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TargetType.Descriptor instead.
func (TargetType) EnumDescriptor() ([]byte, []int) {
	return file_proto_analytics_proto_rawDescGZIP(), []int{0}
}

type Point struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Az float32 `protobuf:"fixed32,1,opt,name=az,proto3" json:"az,omitempty"`
	P  float32 `protobuf:"fixed32,2,opt,name=p,proto3" json:"p,omitempty"`
	T  int64   `protobuf:"varint,3,opt,name=t,proto3" json:"t,omitempty"`
}

func (x *Point) Reset() {
	*x = Point{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_analytics_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Point) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Point) ProtoMessage() {}

func (x *Point) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Point.ProtoReflect.Descriptor instead.
func (*Point) Descriptor() ([]byte, []int) {
	return file_proto_analytics_proto_rawDescGZIP(), []int{0}
}

func (x *Point) GetAz() float32 {
	if x != nil {
		return x.Az
	}
	return 0
}

func (x *Point) GetP() float32 {
	if x != nil {
		return x.P
	}
	return 0
}

func (x *Point) GetT() int64 {
	if x != nil {
		return x.T
	}
	return 0
}

type SensorBatchRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Y  TargetType `protobuf:"varint,1,opt,name=y,proto3,enum=radman.ingestion.v1.TargetType" json:"y,omitempty"`
	La float64    `protobuf:"fixed64,2,opt,name=la,proto3" json:"la,omitempty"`
	Lo float64    `protobuf:"fixed64,3,opt,name=lo,proto3" json:"lo,omitempty"`
	Al float64    `protobuf:"fixed64,4,opt,name=al,proto3" json:"al,omitempty"`
	P  []*Point   `protobuf:"bytes,5,rep,name=p,proto3" json:"p,omitempty"`
}

func (x *SensorBatchRequest) Reset() {
	*x = SensorBatchRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_analytics_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SensorBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SensorBatchRequest) ProtoMessage() {}

func (x *SensorBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SensorBatchRequest.ProtoReflect.Descriptor instead.
func (*SensorBatchRequest) Descriptor() ([]byte, []int) {
	return file_proto_analytics_proto_rawDescGZIP(), []int{1}
}

func (x *SensorBatchRequest) GetY() TargetType {
	if x != nil {
		return x.Y
	}
	return TargetType_UFO
}

func (x *SensorBatchRequest) GetLa() float64 {
	if x != nil {
		return x.La
	}
	return 0
}

func (x *SensorBatchRequest) GetLo() float64 {
	if x != nil {
		return x.Lo
	}
	return 0
}

func (x *SensorBatchRequest) GetAl() float64 {
	if x != nil {
		return x.Al
	}
	return 0
}

func (x *SensorBatchRequest) GetP() []*Point {
	if x != nil {
		return x.P
	}
	return nil
}

type SensorBatchResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error   string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *SensorBatchResponse) Reset() {
	*x = SensorBatchResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_analytics_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SensorBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SensorBatchResponse) ProtoMessage() {}

func (x *SensorBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SensorBatchResponse.ProtoReflect.Descriptor instead.
func (*SensorBatchResponse) Descriptor() ([]byte, []int) {
	return file_proto_analytics_proto_rawDescGZIP(), []int{2}
}

func (x *SensorBatchResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SensorBatchResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_proto_analytics_proto protoreflect.FileDescriptor

var file_proto_analytics_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x6e, 0x61, 0x6c, 0x79, 0x74, 0x69, 0x63,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x13, 0x72, 0x61, 0x64, 0x6d, 0x61, 0x6e, 0x2e,
	0x69, 0x6e, 0x67, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x22, 0x33, 0x0a, 0x05,
	0x50, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x61, 0x7a, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x02, 0x52, 0x02, 0x61, 0x7a, 0x12, 0x0c, 0x0a, 0x01, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02,
	0x52, 0x01, 0x70, 0x12, 0x0c, 0x0a, 0x01, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x01,
	0x74, 0x22, 0x9d, 0x01, 0x0a, 0x12, 0x53, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x42, 0x61, 0x74, 0x63,
	0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2d, 0x0a, 0x01, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x1f, 0x2e, 0x72, 0x61, 0x64, 0x6d, 0x61, 0x6e, 0x2e, 0x69, 0x6e, 0x67,
	0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74,
	0x54, 0x79, 0x70, 0x65, 0x52, 0x01, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x6c, 0x61, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x01, 0x52, 0x02, 0x6c, 0x61, 0x12, 0x0e, 0x0a, 0x02, 0x6c, 0x6f, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x01, 0x52, 0x02, 0x6c, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x61, 0x6c, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x01, 0x52, 0x02, 0x61, 0x6c, 0x12, 0x28, 0x0a, 0x01, 0x70, 0x18, 0x05, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x72, 0x61, 0x64, 0x6d, 0x61, 0x6e, 0x2e, 0x69, 0x6e, 0x67, 0x65,
	0x73, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x01,
	0x70, 0x22, 0x45, 0x0a, 0x13, 0x53, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x42, 0x61, 0x74, 0x63, 0x68,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x2a, 0x6c, 0x0a, 0x0a, 0x54, 0x61, 0x72, 0x67,
	0x65, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x07, 0x0a, 0x03, 0x55, 0x46, 0x4f, 0x10, 0x00, 0x12,
	0x12, 0x0a, 0x0e, 0x43, 0x52, 0x55, 0x49, 0x53, 0x45, 0x5f, 0x4d, 0x49, 0x53, 0x53, 0x49, 0x4c,
	0x45, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x44, 0x52, 0x4f, 0x4e, 0x45, 0x10, 0x02, 0x12, 0x0e,
	0x0a, 0x0a, 0x48, 0x45, 0x4c, 0x49, 0x43, 0x4f, 0x50, 0x54, 0x45, 0x52, 0x10, 0x03, 0x12, 0x0f,
	0x0a, 0x0b, 0x46, 0x49, 0x47, 0x48, 0x54, 0x45, 0x52, 0x5f, 0x4a, 0x45, 0x54, 0x10, 0x04, 0x12,
	0x07, 0x0a, 0x03, 0x55, 0x41, 0x56, 0x10, 0x05, 0x12, 0x0c, 0x0a, 0x08, 0x41, 0x49, 0x52, 0x50,
	0x4c, 0x41, 0x4e, 0x45, 0x10, 0x06, 0x32, 0x72, 0x0a, 0x10, 0x49, 0x6e, 0x67, 0x65, 0x73, 0x74,
	0x69, 0x6f, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x5e, 0x0a, 0x09, 0x53, 0x65,
	0x6e, 0x64, 0x42, 0x61, 0x74, 0x63, 0x68, 0x12, 0x27, 0x2e, 0x72, 0x61, 0x64, 0x6d, 0x61, 0x6e,
	0x2e, 0x69, 0x6e, 0x67, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65,
	0x6e, 0x73, 0x6f, 0x72, 0x42, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x28, 0x2e, 0x72, 0x61, 0x64, 0x6d, 0x61, 0x6e, 0x2e, 0x69, 0x6e, 0x67, 0x65, 0x73, 0x74,
	0x69, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x42, 0x61, 0x74,
	0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x40, 0x5a, 0x3e, 0x72, 0x61,
	0x64, 0x6d, 0x61, 0x6e, 0x2e, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x2f, 0x69, 0x6e, 0x67, 0x65, 0x73,
	0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2f, 0x69, 0x6e, 0x67, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x76, 0x31,
	0x3b, 0x69, 0x6e, 0x67, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_analytics_proto_rawDescOnce sync.Once
	file_proto_analytics_proto_rawDescData = file_proto_analytics_proto_rawDesc
)

func file_proto_analytics_proto_rawDescGZIP() []byte {
	file_proto_analytics_proto_rawDescOnce.Do(func() {
		file_proto_analytics_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_analytics_proto_rawDescData)
	})
	return file_proto_analytics_proto_rawDescData
}

var file_proto_analytics_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_analytics_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_analytics_proto_goTypes = []interface{}{
	(TargetType)(0),             // 0: radman.ingestion.v1.TargetType
	(*Point)(nil),               // 1: radman.ingestion.v1.Point
	(*SensorBatchRequest)(nil),  // 2: radman.ingestion.v1.SensorBatchRequest
	(*SensorBatchResponse)(nil), // 3: radman.ingestion.v1.SensorBatchResponse
}
var file_proto_analytics_proto_depIdxs = []int32{
	0, // 0: radman.ingestion.v1.SensorBatchRequest.y:type_name -> radman.ingestion.v1.TargetType
	1, // 1: radman.ingestion.v1.SensorBatchRequest.p:type_name -> radman.ingestion.v1.Point
	2, // 2: radman.ingestion.v1.IngestionService.SendBatch:input_type -> radman.ingestion.v1.SensorBatchRequest
	3, // 3: radman.ingestion.v1.IngestionService.SendBatch:output_type -> radman.ingestion.v1.SensorBatchResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_analytics_proto_init() }
func file_proto_analytics_proto_init() {
	if File_proto_analytics_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_analytics_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Point); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_analytics_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SensorBatchRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_analytics_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SensorBatchResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_analytics_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_analytics_proto_goTypes,
		DependencyIndexes: file_proto_analytics_proto_depIdxs,
		EnumInfos:         file_proto_analytics_proto_enumTypes,
		MessageInfos:      file_proto_analytics_proto_msgTypes,
	}.Build()
	File_proto_analytics_proto = out.File
	file_proto_analytics_proto_rawDesc = nil
	file_proto_analytics_proto_goTypes = nil
	file_proto_analytics_proto_depIdxs = nil
}
