redis:
  addr: "redis_db:6379"
  # user و pass از env می‌آن: REDIS_USER, REDIS_PASS

db:
  # dsn از env می‌آد: PROCESSOR_DATABASE_URL

radar:
  h3_resolution: 6
  association_radius_meters: 2000.0
  coast_timeout_seconds: 300

targets_agl:
  UFO: 10000.0
  CRUISE_MISSILE: 100.0
  DRONE: 200.0
  HELICOPTER: 500.0
  FIGHTER_JET: 5000.0
  UAV: 1500.0
  AIRPLANE: 10000.0
